apiVersion: networking.k8s.io/v1
# UPDATE THE API
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # ADD THIS LINE ABOVE
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    # UPDATE THIS LINE ABOVE
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /?(.*)
#           # UPDATE THIS LINE ABOVE
#             backend:
#               serviceName: client-cluster-ip-service
#               servicePort: 3000
#           - path: /api/?(.*)
#           # UPDATE THIS LINE ABOVE
#             backend:
#               serviceName: server-cluster-ip-service
#               servicePort: 5000
spec:
  tls:
    -hosts:
        - k8s-multi.com
        - www.k8s-multi.com
      secretName: k8s-multi-com
  # rules:
  #   - http:
  #       paths:
  #         - path: /?(.*)
  #           pathType: Prefix
  #         # UPDATE THIS LINE ABOVE
  #           backend:
  #             service:
  #               name: client-cluster-ip-service
  #               port: 
  #                 number: 3000
  #         - path: /api/?(.*)
  #           pathType: Prefix
  #         # UPDATE THIS LINE ABOVE
  #           backend:
  #             service:
  #               name: server-cluster-ip-service
  #               port: 
  #                 number: 5000
  rules:
    - host: k8s-multi.com
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
          # UPDATE THIS LINE ABOVE
            backend:
              service:
                name: client-cluster-ip-service
                port: 
                  number: 3000
          - path: /api/?(.*)
            pathType: Prefix
          # UPDATE THIS LINE ABOVE
            backend:
              service:
                name: server-cluster-ip-service
                port: 
                  number: 5000
    - host: www.k8s-multi.com
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
          # UPDATE THIS LINE ABOVE
            backend:
              service:
                name: client-cluster-ip-service
                port: 
                  number: 3000
          - path: /api/?(.*)
            pathType: Prefix
          # UPDATE THIS LINE ABOVE
            backend:
              service:
                name: server-cluster-ip-service
                port: 
                  number: 5000